### ISSUE TITLE
Blockquote style error

### ISSUE THREAD

**Issue by taozina0587** [Morganwan90/Lightblue-siyuan-theme#11]
Friend, look how the blockquote is when activated in a list with hierarchy! The blue effect at the top is stretched and distorted.

![image](https://user-images.githubusercontent.com/90691302/174240973-4682a567-4682-40ba-ab0a-dd6b1144738f.png)

**Comment by Morganwan90** [comment]
Hi, thanks for the feedback.
I have made some adjustments to the style of blockquote under the list item，which will take effect in the next release.
