### ISSUE TITLE
关于反链浮窗显示的建议

### ISSUE THREAD

**Issue by Hyd19** [Morganwan90/Lightblue-siyuan-theme#12]
鼠标悬停于段落反链角标，各引用项显示到文档名一级，需要鼠标移动至文档名上方，才显示具体层级，不是很直观，如下图。内容多的话，需要一条条去寻找所需的内容。
![image](https://user-images.githubusercontent.com/84370053/193715839-1046e8e7-13ac-4913-a434-2c97da13fa16.png)
![image](https://user-images.githubusercontent.com/84370053/193715868-ecaf718e-2436-4c47-be80-2f0b45a75806.png)
思源默认主题是自动显示到具体路径的，很直观，如下图：
![image](https://user-images.githubusercontent.com/84370053/193716144-b961d3a1-08a3-4db9-81c1-93b1a4453539.png)
是否可以借鉴这一特点作改进？

**Comment by Morganwan90** [comment]
嗯 感谢建议，已经提了PR了，等D大部署后应该就可以了
