### ISSUE TITLE
拖动块时的示意框不明了

### ISSUE THREAD

**Issue by Hyd19** [Morganwan90/Lightblue-siyuan-theme#13]
默认主题下，拖动块会有横杠提示进行何种操作：
![2](https://user-images.githubusercontent.com/84370053/194994733-bdd01fbe-c4ad-492e-8a1f-8c00cf5ccea6.gif)

而在Lightblue中没有，导致拖动块时很难把握拖动效果：
![1](https://user-images.githubusercontent.com/84370053/194994779-fb2bf135-67cc-46c4-947e-020d9784126c.gif)

建议加上这个横杠，拖动块时更方便。

**Comment by Morganwan90** [comment]
感谢建议，已提交PR，待D大部署。
