### ISSUE TITLE
行内代码高亮一些

### ISSUE THREAD

**Issue by itachaaa** [Morganwan90/Lightblue-siyuan-theme#17]
![image](https://user-images.githubusercontent.com/31896600/233251323-de838320-d17b-42ba-9641-5da4b64eea77.png)
如图行内代码是淡灰色，不是很明显，能否改为浅红色呢？类似 savor 的颜色。
或者是否可以提供代码片段来自定义修改

**Comment by itachaaa** [comment]
> 
我尝试修改了主题文件夹下的 theme.css 文件中的 行内代码对应的颜色，从inherit修改为 #d23f31，重启或修改主题后依然没有生效。

**Comment by Morganwan90** [comment]
感谢反馈，已尝试修改更新，谢谢！

**Comment by itachaaa** [comment]
还有个小优化：
按斜杠时，有一些主题会使用多列的形式展示选项，貌似这样会更方便一些。
![image](https://github.com/Morganwan90/Lightblue-siyuan-theme/assets/31896600/a46dd31e-6089-43d1-b70e-85c8099c92d9)

**Comment by Morganwan90** [comment]
> 还有个小优化： 按斜杠时，有一些主题会使用多列的形式展示选项，貌似这样会更方便一些。 ![image](https://user-images.githubusercontent.com/31896600/237083396-a46dd31e-6089-43d1-b70e-85c8099c92d9.png)

之前好像就是这样的...但是后来因为啥给删了忘记了.....我下次把他加回来....
