### ISSUE TITLE
如何修改CSS以去除背景毛玻璃效果？

### ISSUE THREAD

**Issue by BasaNite16** [Morganwan90/Lightblue-siyuan-theme#2]
非常喜欢您写的CSS，但是背景的毛玻璃效果似乎增加了运行性能负担，软件操作比较卡顿不流畅。鄙人不懂css，请教应该如何设置能去除背景效果。

**Comment by Morganwan90** [comment]
[Light-Blue-V.zip](https://github.com/Morganwan90/Lightblue-siyuan-theme/files/7783909/Light-Blue-V.zip)
这个无法通过简单添加或删除某行来弄，我尝试修改了一下，请将压缩文件解压至【数据空间文件夹】\conf\appearance
重启思源，在设置-外观-主题中选择LIGHT-BLUE-V
烦请帮忙感受一下效果咋样，我也想着要不要就把毛玻璃去掉算了。
![截图_20215828045818](https://user-images.githubusercontent.com/61633409/147548504-84806b9d-c206-4fd1-837c-e32f562da37d.png)

**Comment by BasaNite16** [comment]
感谢，已经换上了。个人感觉效果也挺好的，流畅的同时清爽美观。只是去掉毛玻璃后，这个灰色多边形背景似乎略显突兀，之前更有整体感。

**Comment by Morganwan90** [comment]
好的好的，那我再考虑一下哈，谢谢你喜欢我的主题哈

**Comment by Morganwan90** [comment]
> 感谢，已经换上了。个人感觉效果也挺好的，流畅的同时清爽美观。只是去掉毛玻璃后，这个灰色多边形背景似乎略显突兀，之前更有整体感。

下个版本完全取消了毛玻璃，等D大部署以后兄弟你再试试~

**Comment by BasaNite16** [comment]
> 下个版本完全取消了毛玻璃，等D大部署以后兄弟你再试试~

已经更新尝试了，还是更偏向上次light-blue-v纯白的效果，因为现在背景与文字交织，看起来不是特别清楚。
