### ISSUE TITLE
希望作者能适配集市上架的新规范

### ISSUE THREAD

**Issue by frostime** [Morganwan90/Lightblue-siyuan-theme#20]
Light-blue 和 dark-blue 都是我非常喜欢的主题，也一直再用。

最近思源更新了新的版本后，规范了主题开发的要求。而不符合规范的包可能会在后期逐步下架。

- https://github.com/siyuan-note/theme-sample
- https://github.com/siyuan-note/bazaar/issues/1105

我注意到作者近几个星期都没有做过适配，希望您有空能拨冗适配一下新的开发规范。对于主题而言其实工作量不大，主要就是需要打个包发布release。

**Comment by Morganwan90** [comment]
尝试按照现在的要求弄了一下，感谢反馈

**Comment by frostime** [comment]
抱歉上面放错链接了。。。:-(

https://github.com/siyuan-note/theme-sample

**Comment by Morganwan90** [comment]
> 抱歉上面放错链接了。。。:-(
> 
> https://github.com/siyuan-note/theme-sample

嗯没事，我看已经成功了，应该是符合了...
