### ISSUE TITLE
斜杠面板在同时开启左右侧边栏时，界面会挤兑在一起

### ISSUE THREAD

**Issue by EaMarWi** [Morganwan90/Lightblue-siyuan-theme#21]
如图，斜杠面板在同时开启左右侧边栏时，界面会挤兑在一起，快捷键名称直接掩盖掉命令名称。
![image](https://github.com/Morganwan90/Lightblue-siyuan-theme/assets/72482686/e3bf0fc6-e61f-4406-9d97-052b090c743e)
希望可以优化一下，让其和不同时开启左右侧边栏时下一样（如图）感谢！
![image](https://github.com/Morganwan90/Lightblue-siyuan-theme/assets/72482686/327f260d-893d-421b-aac7-5af326fad183)
虽然这里显示的是Dark Blue主题，但是light Blue主题也有这个问题。

**Comment by Morganwan90** [comment]
感谢反馈 已尝试修复，谢谢！
