### ISSUE TITLE
主题反馈

### ISSUE THREAD

**Issue by leipeng111** [Morganwan90/Lightblue-siyuan-theme#22]
主题很好用~
提个反馈，光标在正文，然后按左右（<-，->）键的时候，左侧大纲栏对应的位置会抖动

**Comment by Morganwan90** [comment]
抱歉，我这边暂时无法复现。
请尝试关闭其他插件或挂件试一下，看看是否由它们引起的..

**Comment by leipeng111** [comment]
好的我试试



| |
penglei
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月22日 17:23 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Morganwan90/Lightblue-siyuan-theme] 主题反馈 (Issue #22) |

抱歉，我这边暂时无法复现。
请尝试关闭其他插件或挂件看看。

**Comment by Morganwan90** [comment]
嗯嗯 也可能是我复现的方式不对 如果还存在的话 可以录屏操作我看下
