### ISSUE TITLE
pdf引用和标记颜色混合看不清，希望大佬优化下

### ISSUE THREAD

**Issue by Jiangshuon** [Morganwan90/Lightblue-siyuan-theme#25]
我记得好像之前版本标记颜色是黄色的

![c1fa46f3cf83cfabd6e2c1ad6d3524f](https://github.com/Morganwan90/Lightblue-siyuan-theme/assets/67137548/3a327155-c190-45ab-9953-0709571eb402)

**Comment by Morganwan90** [comment]
恢复成了默认黄色，请下个版本尝试看看
