### ISSUE TITLE
希望大佬把标签框的大小稍微改小一点

### ISSUE THREAD

**Issue by Jiangshuon** [Morganwan90/Lightblue-siyuan-theme#26]
特别是一级标题和二级标题，已经触碰到标题线了

![30d89aa806ba1b8580f9a362f63d69b](https://github.com/Morganwan90/Lightblue-siyuan-theme/assets/67137548/8a3c7472-d995-4dcd-93e1-4f1e3369e4a5)

**Comment by Morganwan90** [comment]
尝试做了些修改，下个版本看看
