### ISSUE TITLE
自定义设置

### ISSUE THREAD

**Issue by Zijinn** [Morganwan90/Lightblue-siyuan-theme#27]
我非常喜欢这款主题，是否可以提供自定义设置选项。

**Comment by FIX198200** [comment]
![image](https://github.com/Morganwan90/Lightblue-siyuan-theme/assets/121087710/dfefd7ec-b2b2-42d0-b283-0aae583bdfad)
您好，思源新版本的导出界面显示出现问题，您能更新一下主题吗？

**Comment by Morganwan90** [comment]
> 我非常喜欢这款主题，是否可以提供自定义设置选项。

@Zijinn 非常感谢您的喜欢，但是由于我现在用思源比较少，对于bug的修复我会根据自身时间积极跟进。
但对于这个自定义的选项，我主要还不知道怎么弄...这个是思源的新特性么？是否有相关的文档可以让我对这个功能做跟进？

**Comment by Morganwan90** [comment]
> ![image](https://private-user-images.githubusercontent.com/121087710/316209300-dfefd7ec-b2b2-42d0-b283-0aae583bdfad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNTg4OTgsIm5iZiI6MTcxMTI1ODU5OCwicGF0aCI6Ii8xMjEwODc3MTAvMzE2MjA5MzAwLWRmZWZkN2VjLWIyYjItNDJkMC1iMjgzLTBhYWU1ODNiZGZhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQwNTM2MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWIyY2I2NWI2ZDlkNjFiOTdiODVjMzc3YzJmN2ZkMjBiYTJlMmMwMGI2YzMwNzhmY2E5YjM3ODdiNWEzNmIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-wCOixqElWEEPnwt--XxeLyDulTpO_jUh-tTzVIm2Yc) 您好，思源新版本的导出界面显示出现问题，您能更新一下主题吗？

@FIX198200 好的，我会尝试修正并在下一个版本中更新，请到时候更新看下是否可以满足需求。

**Comment by Zijinn** [comment]
@Morganwan90  非常感谢您的贡献！我也是刚开始使用该软件，我将尝试在theme.css中自行进行修改设定，我发现其中的备注已经非常详细，再次感谢！

**Comment by Morganwan90** [comment]
> @Morganwan90 非常感谢您的贡献！我也是刚开始使用该软件，我将尝试在theme.css中自行进行修改设定，我发现其中的备注已经非常详细，再次感谢！

好的，谢谢你喜欢我的主题！
