### ISSUE TITLE
作者能有时间改改不？

### ISSUE THREAD

**Issue by bawtuflf** [Morganwan90/Lightblue-siyuan-theme#29]
1、在我使用任务列表插件时，右击任务，就会黑屏。
2、看PDF时，字体看着就能难受，可能是黑背景与白字，字又细的原因，看着很累！

**Comment by Morganwan90** [comment]
你好吖。
问题1我改了下，应该没问题了，等主题更新完成后可以试试。
问题2不太明白具体需求，是指dark-blue下的pdf浏览么
