### ISSUE TITLE
手机端的文件树侧边栏不透明度过低

### ISSUE THREAD

**Issue by Tlonglan** [Morganwan90/Lightblue-siyuan-theme#3]
最新版的手机端的文件树侧边栏不透明度过低了，基本看不到内容，希望可以提高一点不透明度

![image](https://user-images.githubusercontent.com/38731172/150055757-e910a9d5-d1f6-4c52-95c7-6f74fdde113e.png)

**Comment by Morganwan90** [comment]
好的，移动端之前都没考虑整...我改一下
