### ISSUE TITLE
分割线变成两条，希望可以修复这个bug

### ISSUE THREAD

**Issue by EdwardOwl** [Morganwan90/Lightblue-siyuan-theme#30]
![Clip_2024-08-13_15-00-42](https://github.com/user-attachments/assets/ec6772b6-31c1-46ea-bba5-d99062e29559)

**Comment by EdwardOwl** [comment]
Dark-blue主题也有一样的bug

**Comment by Morganwan90** [comment]
我有一段时间没用siyuan...新功能有点跟不上....
这个分割线是在什么场景下出现的，似乎看起来不是直接在文档出现..

**Comment by EdwardOwl** [comment]
> 我有一段时间没用siyuan...新功能有点跟不上.... 这个分割线是在什么场景下出现的，似乎看起来不是直接在文档出现..

您好，分割线就是siyuan里面md语法的---
会显示如图所示的两条分割线

**Comment by EdwardOwl** [comment]
一条蓝色分割线，一条浅灰色分割线

**Comment by EdwardOwl** [comment]
![Clip_2024-08-19_17-04-41](https://github.com/user-attachments/assets/7dcf08e6-99f5-4617-8282-8b82bdbad8c4)
这张图是我新建一个工作空间后，下载light blue主题，使用---创建分割线出现的情况。有着两条分割线
同样的情况在dark blue主题中亦有发生。

![Clip_2024-08-19_17-06-35](https://github.com/user-attachments/assets/7b224622-a4de-4daa-8d7c-027a66bf7720)
在默认主题下如上图，---创建的分割线只有一条。

**Comment by Morganwan90** [comment]
soga...我晚上弄一下...

**Comment by Morganwan90** [comment]
已修复，谢谢你用我的主题！

**Comment by EdwardOwl** [comment]
> 已修复，谢谢你用我的主题！

也谢谢你维护这个主题
