### ISSUE TITLE
文字内容「标记」配色问题

### ISSUE THREAD

**Issue by wyn-ying** [Morganwan90/Lightblue-siyuan-theme#4]
标题和正文中的「标记」（cmd+E）配色比较奇怪，看起来是文字颜色和背景颜色重了，导致看不见字（图1）。只有鼠标放上去才能看见文字（图2）。这个是feature吗？如果是之前没注意到，建议改一下~
图1
![image](https://user-images.githubusercontent.com/13808754/157196424-a475149f-2215-4f1e-96fb-b63c63ee30dc.png)

图2
![image](https://user-images.githubusercontent.com/13808754/157196701-40341f55-745d-49a3-96c9-38751c0a9d0e.png)

**Comment by Morganwan90** [comment]
标记格式是特意改成的“挖空效果”，当时是用作复习的时候标记答案的.....
算是个特性吧..

**Comment by wyn-ying** [comment]
了解，蛮有趣的设计。。我再看下这个格式的其他替代方案吧，总体体验还是非常棒的~

**Comment by Morganwan90** [comment]
![截图_20222310062342](https://user-images.githubusercontent.com/61633409/157642227-fdc12ade-b72c-4332-99d4-850ac14444d6.png)
可以选择把theme.css这段注释（把 ‘/ ’ 删掉），也可以更改这段代码哈。
