### ISSUE TITLE
打开了PDF后，背景模糊效果失效！

### ISSUE THREAD

**Issue by xiaoyoucheng** [Morganwan90/Lightblue-siyuan-theme#5]
如图所示，打开PDF后会导致背景模糊失效
![image](https://user-images.githubusercontent.com/33143581/157655822-f747d0a1-446a-44bc-ae6c-cde7c6c47bb4.png)

**Comment by Morganwan90** [comment]
感谢反馈
这两天比较忙，尽快修复。

**Comment by xiaoyoucheng** [comment]
> 感谢反馈 这两天比较忙，尽快修复。

啊，感谢，实在拿css没辙，只能求助了哈哈。

**Comment by Morganwan90** [comment]
> 啊，感谢，实在拿css没辙，只能求助了哈哈。

改了一下，已提交集市哈，要等D大部署了才生效

**Comment by xiaoyoucheng** [comment]
> > 啊，感谢，实在拿css没辙，只能求助了哈哈。
> 
> 改了一下，已提交集市哈，要等D大部署了才生效

好滴， 我看看哈。

**Comment by xiaoyoucheng** [comment]
> > 啊，感谢，实在拿css没辙，只能求助了哈哈。
> 
> 改了一下，已提交集市哈，要等D大部署了才生效

![image](https://user-images.githubusercontent.com/33143581/158099623-6d3f1ba1-a4eb-4178-99e8-a18289b9c1c0.png)
测试正常了
