### ISSUE TITLE
请求将弹出的双链面板改为竖向

### ISSUE THREAD

**Issue by LiveGrow** [Morganwan90/Lightblue-siyuan-theme#7]
开发者大佬好，非常感谢您开发这么好看又好用的主题，但是我在写笔记的过程中，发现横向的双链面板显示的内容太少了，不利于看到想要引用的内容，如图：
![image](https://user-images.githubusercontent.com/53644808/165082937-5de0153f-17eb-40e3-826e-968d24ce6663.png)
可以在下次的版本更新中将双链面板恢复为纵向吗？

**Comment by Morganwan90** [comment]
感谢反馈，已改，等D大部署哈

**Comment by LiveGrow** [comment]
感恩大佬！
