### ISSUE TITLE
插入表情时弹出窗口太小

### ISSUE THREAD

**Issue by LiveGrow** [Morganwan90/Lightblue-siyuan-theme#8]
今天在插入表情的时候发现弹出的窗口高度太小了，请求大佬有时间了修复一下
![image](https://user-images.githubusercontent.com/53644808/166453944-b3690842-c240-471e-896f-a0cc38a1d111.png)

**Comment by Morganwan90** [comment]
感谢反馈，已修订，等D大部署。
