### ISSUE TITLE
没有自定义模板？

### ISSUE THREAD

**Issue by zhanfen0716** [Morganwan90/Lightblue-siyuan-theme#9]
而且反馈问题还得注册GITHUB账号，不过思源主题Lightblue确实很好看

**Comment by Morganwan90** [comment]
感谢反馈，自定义模板已提交，等D大部署，请将custom.css移至\data\widgets下使用。
反馈途经的话....除了github也能在QQ群里找到我，昵称是一样的，但是平时工作比较忙，可能上的没那么勤。
谢谢你喜欢我的主题。

**Comment by zhanfen0716** [comment]
好的，期待您的主题越来越好
